### ISSUE TITLE
Include network mask for node

### ISSUE THREAD

**Issue by smsearcy** [smsearcy/mesh-info#115]
From @na7kr (in other issue):

I have a request can you add another column to the table and show the range on nodes, IE /27 or /28 or 10.234.160.224/27 whatever it reports? ( would better 10.234.160.224-245 ) then flag any dups..

As we have some/or had some do not know if they fixed them yet.

**Comment by smsearcy** [comment]
@NA7KR, which network is this where you're looking for the mask, the local LAN network?

Unfortunately, it doesn't appear that information is available in the `sysinfo.json`, but I want to clarify in case I'm missing something.

**Comment by NA7KR** [comment]
Hi Scott

Is there any update on maps that will work again?

 

Have a lovely Christmas. 

 

Kevin

**Comment by smsearcy** [comment]
Kevin-

I'm intending to make some time to get the tiles working in the next week or so. 

Scott

**Comment by smsearcy** [comment]
I double checked the `sysinfo.json` from the latest firmware (v1.13) and it just has IP addresses for network interfaces, no masks or CIDR notation.  So I cannot include the network mask in Mesh Info unless that is added.
