### ISSUE TITLE
Map tiles no longer available

### ISSUE THREAD

**Issue by smsearcy** [smsearcy/mesh-info#118]
The default URL for the map tiles doesn't work anymore.

https://maps.stamen.com/stadia-partnership/

**Comment by NA7KR** [comment]
Looks like stamen-tiles-a.a.ssl.fastly.net the subdomain has been removed.

**Comment by smsearcy** [comment]
I've updated my local installation, will need to remove the default from the code.

**Comment by NA7KR** [comment]
What file? And what to remove?

**Comment by NA7KR** [comment]
Hi Scott, What files and what do I need to remove?

**Comment by smsearcy** [comment]
@NA7KR, sorry for the delayed response.  You'll need a URL for a tile server (I used https://stadiamaps.com for mine), and then update the `.env` file (likely in `/opt/mesh-info/src/.env`) with the following (using the appropriate attribution):

```
MESH_INFO_MAP_TILE_URL="https://tiles.stadiamaps.com/tiles/stamen_terrain/{z}/{x}/{y}{r}.png"
MESH_INFO_MAP_TILE_ATTRIBUTION=""
```
