### ISSUE TITLE
How to Install?

### ISSUE THREAD

**Issue by jeepnjonny** [smsearcy/mesh-info#120]
I'd like to try out your project but don't have enough developer experience to know all the steps to install your project. Do you have a little guidance?

**Comment by jeepnjonny** [comment]
found the install documentation in the obvious place that I didn't look before: /docs/installation.rst

**Comment by smsearcy** [comment]
Sorry for the delay in responding.  The docs are published on the web here: https://mesh-info-ki7onk.readthedocs.io/

I have had some issues lately with the "collector" freezing, I need to look into that more.  How large of a mesh are you on?

**Comment by smsearcy** [comment]
Oops, one more thing.  I just realized I never merged/published the changes with the map tile service I was using.  I need to get that and a security update pushed in the next couple of days.

**Comment by jeepnjonny** [comment]
I've got it up and running, really enjoying the data! I had previously setup a tile server, so I figured out the config to use that. The mesh here is about 38 nodes, mostly tunnel but building out the RF, we're on the supernode mesh! KG7KMV
