### ISSUE TITLE
WireGuard

### ISSUE THREAD

**Issue by NA7KR** [smsearcy/mesh-info#122]
May  4 16:35:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.117.8>May  4 16:35:40 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.27.66>May  4 16:35:40 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.27.66>May  4 16:35:40 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.27.66>May  4 16:35:40 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.27.66>May  4 16:35:40 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.27.66>May  4 16:35:41 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.252.2>May  4 16:35:41 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mInvalid JSON response         #033[0m #033[36mexc#033[0m=#033[35mJSONDecodeError('Expecting value: line 18 column 7 (char 4>May  4 16:35:43 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.114.1>May  4 16:35:43 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.207.1>May  4 16:35:43 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.247.1>May  4 16:35:44 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.252.2>May  4 16:35:44 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.252.2>May  4 16:35:44 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.252.2>May  4 16:35:44 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.252.2>May  4 16:35:44 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.252.2>May  4 16:35:45 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.142.2>May  4 16:35:46 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.41.8.>May  4 16:35:46 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.76.209.74', po>May  4 16:35:46 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.156.7>May  4 16:35:47 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.166.1>May  4 16:35:47 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.71.25>May  4 16:35:48 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.243.1>May  4 16:35:48 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.110.3>May  4 16:35:48 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.110.3>May  4 16:35:48 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.110.3>May  4 16:35:48 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.110.3>May  4 16:35:48 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.110.3>M
![Untitled](https://github.com/smsearcy/mesh-info/assets/6289433/e1ac834a-ce42-4cd1-9b0f-87730f6eb625)

and it looks like collector stops. thes iis with new Arden firmware

**Comment by NA7KR** [comment]
May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.27.66>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.27.66>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.100.43.106', p>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.184.156.55', p>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.94.18.16', por>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.248.155.181', >May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.15.212.4', por>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.114.1>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.165.69.122', p>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.4.250.63', por>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.78.128.131', p>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.154.252.140', >

**Comment by NA7KR** [comment]
May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             
#033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.252.2>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type            
 #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.27.66>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             
 #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.27.66>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             
 #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.27.66>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             
 #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.27.66>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             
 #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.27.66>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              
 #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.100.43.106', p>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              
 #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.184.156.55', p>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              
 #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.94.18.16', por>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              
 #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.248.155.181', >May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              
 #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.15.212.4', por>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mUnknown link type             
 #033[0m #033[36merror#033[0m=#033[35mWIREGUARD#033[0m #033[36mnode_ip#033[0m=#033[35m10.114.1>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              
 #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.165.69.122', p>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              
 #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.4.250.63', por>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error              
 #033[0m #033[36mexc#033[0m=#033[35mClientConnectorError(ConnectionKey(host='10.78.128.131', p>May  4 16:50:38 na7kr-meshinfo python[461]: [#033[33m#033[1mwarning  #033[0m] #033[1mConnection error

**Comment by smsearcy** [comment]
Thank you for reporting this, I will look into this in the next couple of days.

**Comment by smsearcy** [comment]
It's just a warning, the nodes should still be collected, the link type will just be "Unknown", but it's an easy fix to add the new WIREGUARD type.

I think this is unrelated to the stability issues, which I have some ideas about but need to do some more experimenting.

**Comment by smsearcy** [comment]
I pushed updates that will properly handle the Wireguard tunnels.  Upgrade instructions [here](https://mesh-info-ki7onk.readthedocs.io/en/latest/installation.html#upgrading).

I think the collector stopping is due to a timeout not being properly handled, causing it to get stuff.  I've got an idea of something to try, will let you know what I figure out.
