### ISSUE TITLE
Firmware list sorts

### ISSUE THREAD

**Issue by Orv** [smsearcy/mesh-info#48]
Under the Node list, the Firmware column sort should be a "natural" sort - lowest number first, rather than sorting on the first digit.
I.e., 1866 should be at end of the sorted list.  This would be very helpful.

**Comment by smsearcy** [comment]
That's a good idea.  They're being sorted as strings because they aren't real numbers.  And it's in Javascript, so I'll have to see what I can do.

**Comment by smsearcy** [comment]
I setup a custom sort for the firmware version column so that it is sorting in the natural order now.  Thank you for the suggestion!
