### ISSUE TITLE
Node colors

### ISSUE THREAD

**Issue by Orv** [smsearcy/mesh-info#49]
Other maps have standardized on blue for 3 GHz; Grey is reserved for no RF (e.g., hAP AC).  Recommend you adopt these to reduce confusion.

**Comment by smsearcy** [comment]
Thank you for reporting this. I think this might be related to a typo Eric noticed, that the "Z" is capitalized for the 3 GHz band. I'll make sure I get this fixed with the other wording changes that were submitted.

**Comment by smsearcy** [comment]
After thinking about this a little more, I'm going to make a small patch so that the blue icon is associated with "3GHZ" to fix this immediate issue.
